// 全局存储 Key 常量，对应原项目 com.github.tvbox.osc.util.HawkConfig
class HawkConfig {
  HawkConfig._();

  static const String apiUrl = 'api_url';
  static const String defaultApiUrl = 'https://9280.kstore.vip/newwex.json'; // 测试默认源
  static const String epgUrl = 'epg_url';
  static const String showPreview = 'show_preview';
  static const String apiHistory = 'api_history';
  static const String apiLineList = 'api_line_list';
  static const String apiLineSource = 'api_line_source';
  static const String liveApiHistory = 'live_api_history';
  static const String epgHistory = 'epg_history';
  static const String homeApi = 'home_api';
  static const String defaultParse = 'parse_default';
  static const String debugOpen = 'debug_open';
  static const String parseWebview = 'parse_webview';
  static const String ijkCodec = 'ijk_codec';
  static const String playType = 'play_type'; // 0 系统 1 ijk 2 exo 10 MXPlayer
  static const String livePlayType = 'live_play_type';
  static const String playRender = 'play_render';
  static const String playScale = 'play_scale';
  static const String livePlayScale = 'live_play_scale';
  static const String playTimeStep = 'play_time_step';
  static const String dohUrl = 'doh_url';
  static const int defaultHomeRec = 1;
  static const String homeRec = 'home_rec'; // 0 豆瓣热播 1 数据源推荐 2 历史
  static const String historyNum = 'history_num';
  static const String searchView = 'search_view'; // 0 列表 1 缩略图
  static const String liveChannel = 'last_live_channel_name';
  static const String liveChannelReverse = 'live_channel_reverse';
  static const String liveCrossGroup = 'live_cross_group';
  static const String liveConnectTimeout = 'live_connect_timeout';
  static const String liveShowNetSpeed = 'live_show_net_speed';
  static const String liveShowResolution = 'live_show_resolution';
  static const String liveShowTime = 'live_show_time';
  static const String fastSearchMode = 'fast_search_mode';
  static const String subtitleTextSize = 'subtitle_text_size';
  static const String subtitleTimeDelay = 'subtitle_time_delay';
  static const String sourcesForSearch = 'checked_sources_for_search';
  static const String homeRecStyle = 'home_rec_style';
  static const String nowDate = 'now_date';
  static const String remoteTvbox = 'remote_tvbox_host';
  static const String ijkCachePlay = 'ijk_cache_play';
  static const String playerIsLive = 'player_is_live';
  static const String dohJson = 'doh_json';
  static const String liveGroupIndex = 'live_group_index';
  static const String liveGroupList = 'live_group_list';
  static const String liveApiUrl = 'live_api_url';
  static const String m3u8Purify = 'm3u8_purify';
  static const String autoSwitchLine = 'auto_switch_line';
  static const String screenDisplay = 'screen_display';
  static const String liveWebHeader = 'live_web_header';
  static const String defaultLoadLive = 'DEFAULT_LOAD_LIVE';
  static const String searchHistory = 'search_history';
  static const String danmuOpen = 'danmu_open';
  static const String danmuMaxLine = 'danmu_max_line';
  static const String danmuSpeed = 'danmu_speed';
  static const String danmuAlpha = 'danmu_alpha';
  static const String danmuSizeScale = 'danmu_size_scale';
  static const String danmuRandomColor = 'danmu_random_color';
  static const String danmuApi = 'danmu_api';
}
